In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
data = pd.read_csv("C:/Users/Bryce Walsh/Downloads/train_MNIST.csv/train.csv")

In [5]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [22]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.

_,m_train = X_train.shape




In [23]:
X_train[:, 0].shape

(784,)

In [25]:
def init_params():
    W1 = np.random.rand(10, 784)-0.5
    b1 = np.random.rand(10, 1)-0.5
    W2 = np.random.rand(10, 10)-0.5
    b2 = np.random.rand(10, 1)-0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    #m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1/m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [26]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent (X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [27]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.1)

Iteration:  0
[8 2 0 ... 8 2 8] [2 0 5 ... 3 6 8]
Accuracy:  0.12065853658536585
Iteration:  10
[8 2 0 ... 2 2 8] [2 0 5 ... 3 6 8]
Accuracy:  0.18490243902439024
Iteration:  20
[8 0 0 ... 2 2 2] [2 0 5 ... 3 6 8]
Accuracy:  0.2614878048780488
Iteration:  30
[8 0 0 ... 2 2 2] [2 0 5 ... 3 6 8]
Accuracy:  0.32609756097560977
Iteration:  40
[8 0 0 ... 2 2 2] [2 0 5 ... 3 6 8]
Accuracy:  0.3713658536585366
Iteration:  50
[8 0 0 ... 3 6 2] [2 0 5 ... 3 6 8]
Accuracy:  0.414
Iteration:  60
[8 0 0 ... 3 6 2] [2 0 5 ... 3 6 8]
Accuracy:  0.4551219512195122
Iteration:  70
[8 0 0 ... 3 6 2] [2 0 5 ... 3 6 8]
Accuracy:  0.4946829268292683
Iteration:  80
[8 0 0 ... 3 6 2] [2 0 5 ... 3 6 8]
Accuracy:  0.5287804878048781
Iteration:  90
[8 0 0 ... 3 6 3] [2 0 5 ... 3 6 8]
Accuracy:  0.5591219512195122
Iteration:  100
[8 0 0 ... 3 6 3] [2 0 5 ... 3 6 8]
Accuracy:  0.5864878048780487
Iteration:  110
[2 0 0 ... 3 6 3] [2 0 5 ... 3 6 8]
Accuracy:  0.6104634146341463
Iteration:  120
[2 0 0 ... 3 6 3] [2 

In [28]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [29]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

[6 5 9 2 1 9 2 9 9 8 9 0 2 2 7 9 5 1 6 2 1 1 6 9 8 0 4 2 3 8 9 9 8 8 2 9 1
 1 1 4 3 2 6 6 3 1 6 6 9 3 1 7 0 3 3 6 4 9 3 4 3 9 7 2 5 0 7 7 0 0 5 3 9 7
 3 5 6 2 0 8 5 6 0 9 3 0 7 3 8 8 0 5 0 9 0 9 3 5 6 8 9 2 1 2 9 1 1 9 9 2 1
 1 0 3 9 0 0 0 8 6 3 4 2 3 3 9 4 2 4 8 6 6 1 9 4 5 9 6 3 7 0 7 0 3 3 2 7 9
 7 2 5 1 5 6 0 5 6 7 8 2 7 8 1 6 1 5 2 6 7 7 2 5 0 3 9 1 7 7 7 7 2 0 0 0 7
 6 8 2 3 5 2 1 8 4 6 1 9 0 2 5 0 2 3 8 0 1 1 4 8 5 2 8 1 6 2 1 4 4 5 1 5 6
 2 1 7 7 5 4 1 4 9 9 6 1 1 7 2 7 5 7 6 4 2 6 8 5 8 8 7 0 6 4 2 4 2 1 6 5 6
 2 6 1 5 8 3 6 9 7 8 1 8 4 0 9 2 9 8 4 6 7 1 0 1 6 1 8 3 8 1 7 0 7 7 6 2 8
 1 8 1 7 3 7 3 8 6 5 6 3 5 4 2 0 0 1 1 1 4 7 2 0 0 7 4 9 8 8 6 7 9 9 6 0 5
 4 1 3 6 7 3 9 4 1 7 5 0 3 3 7 4 7 7 6 3 6 9 4 4 5 5 1 0 0 5 6 3 8 9 3 0 0
 9 1 8 8 5 6 3 2 0 9 2 6 0 9 8 3 1 0 2 4 8 8 0 1 2 9 2 1 0 4 7 3 7 1 6 3 0
 5 7 1 9 1 0 6 1 1 5 2 8 1 9 2 5 5 0 3 3 1 8 1 7 7 8 3 7 7 7 0 1 9 3 9 2 6
 3 1 1 8 8 9 1 8 7 8 5 5 2 0 6 1 7 8 4 2 1 0 2 0 2 6 2 5 5 7 5 1 6 7 2 1 4
 3 7 7 5 6 1 0 0 3 5 2 6 

0.828